version: '3.8'

services:
  librarydb:
    image: postgres:16.3
    container_name: librarydb
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=library
    ports:
      - "5434:5432"

